# Generated by Django 5.0.1 on 2026-01-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration_n_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_round', models.IntegerField(choices=[(1, 'Round 1'), (2, 'Round 2'), (3, 'Round 3 (Physical)')], default=1)),
                ('round_status', models.CharField(choices=[('WAITING', 'Waiting'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='WAITING', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round1Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('completion_time', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r1_score', to='registration_n_login.team')),
            ],
        ),
        migrations.CreateModel(
            name='Round2Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('completion_time', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r2_score', to='registration_n_login.team')),
            ],
        ),
        migrations.CreateModel(
            name='Round3Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('completion_time', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r3_score', to='registration_n_login.team')),
            ],
        ),
    ]
