# Generated by Django 5.0.1 on 2026-01-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round1score',
            name='completion_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='round2score',
            name='completion_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='round3score',
            name='completion_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
