# Generated by Django 5.0.1 on 2026-01-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_round1score_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round1score',
            name='completion_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round2score',
            name='completion_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round3score',
            name='completion_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
