# Generated by Django 5.0.1 on 2026-02-02 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_alter_round1score_completion_time_and_more'),
        ('registration_n_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round3Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('sequence_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BerserkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_illegal', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berserk_logs', to='registration_n_login.team')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='instructor.round3question')),
            ],
        ),
    ]
