# Generated by Django 5.0.1 on 2026-02-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_round3question_berserklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='current_round3_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instructor.round3question'),
        ),
        migrations.AddField(
            model_name='round3question',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
