# Generated by Django 5.2.10 on 2026-01-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('primary_member_name', models.CharField(max_length=100)),
                ('primary_member_email', models.EmailField(max_length=254)),
                ('primary_member_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('supporting_member_name', models.CharField(max_length=100)),
                ('supporting_member_email', models.EmailField(max_length=254)),
                ('supporting_member_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
