# Generated by Django 5.2.10 on 2026-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='supporting_member_dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='supporting_member_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
